### ISSUE TITLE
Spring Boot and slf4j-mock Logback error

### ISSUE THREAD

**Issue by hmmlopez** [s4u/slf4j-mock#182]
**Describe the bug**
I'm getting the following error when using this library with Spring Boot.
java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.simplify4u.slf4jmock.LoggerMock$$Lambda$377/0x0000000801240638 loaded from ...

**To Reproduce**
Chekout source project and run "gradlew build"
https://github.com/hmmlopez/slf4j-mock-issue

**Expected behavior**
Expect to be able to use this library with Spring Boot.

**Comment by slawekjaranowski** [comment]
Please look:
https://github.com/s4u/slf4j-mock/issues/90#issuecomment-873365166

**Comment by hmmlopez** [comment]
Well I've tried this without success.
`dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(group = "ch.qos.logback")
    }
    testImplementation("org.simplify4u:slf4j2-mock:2.3.0")
}`

**Comment by hmmlopez** [comment]
When running test with only mockitoextensions it works fine, but in our case (see project example supplied) there are two test cases, one starting with spring boot test, which loads the application and I think this one is expecting a LoggerFactory of Logback LoggerContext. 

It’s easy to reproduce, create a new project from start.spring.io and add this dependency to it.

**Comment by hmmlopez** [comment]
I've manage to find a solution that works for Gradle, this will exclude the `logback-classic` (and logback-core as transient dependency) from the Test Classpath, but will leave it on the compile and runtime classpath.
```
configurations {
    testImplementation {
        exclude(group = "ch.qos.logback", module = "logback-classic")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.simplify4u:slf4j2-mock:2.3.0")
}
```
