### ISSUE TITLE
DefaultMocks of SimpleLogger uses default answer RETURNS_DEFAULTS

### ISSUE THREAD

**Issue by markusschaefer** [s4u/slf4j-mock#204]
**Describe the bug**
The DefaultMock Spies in LoggerMock are created with the default Answer RETURNS_DEFAULTS from Mockito. 

**To Reproduce**
Create a Junit Test with slf4j2-mock binding to slf4j and a simplelogger.properties. Don't bind any mock to the logger, so that the Default Mock will be used.

**Expected behavior**
As the DefaultMocks are Spies of SimpleLogger, the default Answer should be CALLS_REAL_METHODS, so that the SimpleLogger is used with the existing simplelogger.properties.

**Additional context**
The project contains a lot of unit Tests, but only a few needs mocking of the loggers. All other tests should have a normal logging behaviour with logging to System.out or a file.

**Comment by vitalijr2** [comment]
> The project contains a lot of unit Tests, but only a few needs mocking of the loggers. All other tests should have a normal logging behaviour with logging to System.out or a file.

The good idea.

**Comment by slawekjaranowski** [comment]
Thanks for idea ... I will check it
